local set_abbr = function(lhs, rhs)
    vim.cmd("abbr " .. lhs .. " " .. rhs)
end

set_abbr("adn", "and")
set_abbr("alos", "also")
set_abbr("const_case", "const_cast")
set_abbr("dynamic_case", "dynamic_cast")
set_abbr("fitler", "filter")
set_abbr("funciton", "function")
set_abbr("hepl", "help")
set_abbr("hte", "the")
set_abbr("postion", "position")
set_abbr("reinterpret_case", "reinterpret_cast")
set_abbr("static_case", "static_cast")
set_abbr("straighforward", "straightforward")
set_abbr("teh", "the")
set_abbr("tehn", "then")
set_abbr("tempalte", "template")
set_abbr("waht", "what")

set_abbr(".78.", "..............................................................................")
set_abbr("-78-", "------------------------------------------------------------------------------")
set_abbr("=78=", "==============================================================================")
set_abbr("*78*", "******************************************************************************")
set_abbr("x78x", "******************************************************************************")
