# https://starship.rs/config/

command_timeout = 10000

format = """
[┌───────────────────>](bold green)
[│](bold green) $time: \
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$lua\
$jobs\
$battery\
$status\
$shell\
$line_break\
[└─>](bold green) $character"""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmake]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false

[python]
python_binary = "python3"
disabled = true

[status]
disabled = false
format = "[$symbol$status: $common_meaning]($style)"

[time]
disabled = false
format = "[$time]($style)"
