local utils = require("utils")

utils.set_abbr("adn", "and")
utils.set_abbr("alos", "also")
utils.set_abbr("const_case", "const_cast")
utils.set_abbr("dynamic_case", "dynamic_cast")
utils.set_abbr("fitler", "filter")
utils.set_abbr("funciton", "function")
utils.set_abbr("hepl", "help")
utils.set_abbr("hte", "the")
utils.set_abbr("reinterpret_case", "reinterpret_cast")
utils.set_abbr("static_case", "static_cast")
utils.set_abbr("teh", "the")
utils.set_abbr("tehn", "then")
utils.set_abbr("tempalte", "template")
utils.set_abbr("waht", "what")

utils.set_abbr(".78.", "..............................................................................")
utils.set_abbr("-78-", "------------------------------------------------------------------------------")
utils.set_abbr("=78=", "==============================================================================")
utils.set_abbr("*78*", "******************************************************************************")
utils.set_abbr("x78x", "******************************************************************************")
